### ISSUE TITLE
$count in resource explorer seems to put wrong url

### ISSUE THREAD

**Issue by ddyett** [microsoftgraph/microsoft-graph-explorer-v4#2472]
Open Resource Explorer tab
Expand the drives path
Click $count

Result:
url placed is https://graph.microsoft.com/v1.0/drives/$count which doesn't work as it's not a drive id.  

Expectation

https://graph.microsoft.com/v1.0/drives?$count

**Comment by irvinesunday** [comment]
We use `CountRestrictions` annotations to determine whether or not to add the `$count` segments to paths. If this is not specified in the CSDL, it defaults to `true` --> add the `$count` segment.

**Comment by thewahome** [comment]
Should we add this as a setting when generating the document?

**Comment by irvinesunday** [comment]
No, this should be added to the CSDL by the respective workload teams or by us via XSLT. The annotation would look like:

```XML
<Annotations Target="microsoft.graph.GraphService/drives">
  <Annotation Term="Org.OData.Capabilities.V1.CountRestrictions">
    <Record>
      <PropertyValue Property="Countable" Bool="false" />
    </Record>
  </Annotation>
</Annotations>
```

**Comment by thewahome** [comment]
@irvinesunday should we close this or move it to another repo?

**Comment by irvinesunday** [comment]
> ```
> <Annotations Target="microsoft.graph.GraphService/drives
> ```

@thewahome this was resolved in the metadata. You can close it

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/40403681/0f24c936-f023-4082-99ea-0c45aa8e5147)

**Comment by musale** [comment]
@irvinesunday is this rolled out for all endpoints that support $count? I can still reproduce it on endpoints like /application, /chats etc

**Comment by irvinesunday** [comment]
> @irvinesunday is this rolled out for all endpoints that support $count? I can still reproduce it on endpoints like /application, /chats etc

@musale unfortunately this can only be currently  addressed on a need basis. It might be hard to anticipate all the resources that don't support `/$count`. Ideally, workloads need to explicitly annotate their resources in the metadata to indicate support or otherwise for such operations/paths. The conversion library automatically assumes support (and hence generates the paths) unless explicitly annotated otherwise in the metadata. We are are trying to resolve this by getting workload owners to move to using Typespec as their API definition language. Typespec requires explicit annotations definitions.

**Comment by ElinorW** [comment]
C

> > ```
> > <Annotations Target="microsoft.graph.GraphService/drives
> > ```
> 
> @thewahome this was resolved in the metadata. You can close it if you can confirm that it is resolved in GE
> 
> ![image](https://private-user-images.githubusercontent.com/40403681/334777847-0f24c936-f023-4082-99ea-0c45aa8e5147.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjI2NjYsIm5iZiI6MTcyNDY2MjM2NiwicGF0aCI6Ii80MDQwMzY4MS8zMzQ3Nzc4NDctMGYyNGM5MzYtZjAyMy00MDgyLTk5ZWEtMGM0NWFhOGU1MTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA4NTI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMThjODE2NjI0YzE1MzMxYThiYWRiODA4ZTJkNzliNmYzNzYwNDg4NmNjMmFkNDQ3MWNlYjE2NTViZDVhNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.twGUhWer5CMDVTnn8Su7AtmS6R-OObLbpnxSssw5mVU)

I can confirm that it's resolved on GE, therefore I will go ahead and close this
