### ISSUE TITLE
"Open the permissions panel" in Graph Explorer Not Working

### ISSUE THREAD

**Issue by lingsun5bsjy7** [microsoftgraph/microsoft-graph-explorer-v4#3015]
**Describe the bug**
When running "GET https://graph.microsoft.com/v1.0/admin/people/profileCardProperties" in Graph Explorer, it prompts error 403 and "Permissions for the query are missing on this tab. Open the permissions panel to see the full list of Microsoft Graph permissions and select the permission(s) you want and consent to them from there." under "Modify permissions". But clicking "Open the permissions panel", it redirects to a blank page. 

**To Reproduce**
1. Go to Graph Explorer - https://developer.microsoft.com/en-us/graph/graph-explorer
2. Sign in with the work account. 
3. Enter "https://graph.microsoft.com/v1.0/admin/people/profileCardProperties" and click 'Run query'. 
4. Click 'Modifiy permissions" > "Open the permissions panel". 

**Expected behavior**
The permissions panel opens. 

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/161305554/5979ece0-3dcb-46f4-bcdf-65c8e13bb964)
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/161305554/b08ac057-9e5f-4b3d-be6e-ec74b446b5e5)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Edge, Chrome]

**Comment by ElinorW** [comment]
Fixed by #3000

**Comment by lingsun5bsjy7** [comment]
> Fixed by #3000

Test it just now but seems still not working. May I know when the fix will be done?

**Comment by thewahome** [comment]
@lingsun5bsjy7 this is live now

**Comment by thewahome** [comment]
Hello @lingsun5bsjy7 
These changes are out now.
